services:
  - type: web
    name: dtq-generator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HCTI_USER_ID
        sync: false
      - key: HCTI_API_KEY
        sync: false
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: DISPLAY_TZ
        value: Asia/Kolkata
      - key: EMAIL_NAMAN
        sync: false
      - key: EMAIL_PIYUSH
        sync: false
      - key: EMAIL_AGRIMA
        sync: false
      - key: EMAIL_KAVYA
        sync: false
      - key: EMAIL_ANANYA
        sync: false
