services:
  - type: web
    name: dtq-generator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HCTI_USER_ID
        sync: false
      - key: HCTI_API_KEY
        sync: false
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
      - key: APP_PASSWORD
        sync: false
